### ISSUE TITLE
HLS VI: Add CMR STAC generation capabilities

### ISSUE THREAD

**Issue by madhuksridhar** [NASA-IMPACT/hls-project#13]

**Comment by SwordSaintLancelot** [comment]
The STAC CMR metadata xml file is generated and validated with the general schema. Below is the screenshot showing the assertValid function confirming that the XML created is in accordance with the general schema.
![Image](https://github.com/NASA-IMPACT/hls-project/assets/34275219/7a982cc9-f3f1-4a27-a35f-a0ca886579b0)

In the screenshot, `temp1` variable contains the general `xml` schema while `temp2` contains the `hls-vi` schema. Asserting them with each other does not result in any error.

**Comment by Jeaton1021** [comment]
Waiting on Chuck to review next week before closing out.

**Comment by chuckwondo** [comment]
@SwordSaintLancelot, some major refactoring has landed on the `main` branch, which moves/renames a number of things, most importantly the package folder, which changed from `hls-vi` to `hls_vi` because `hls-vi` is not a valid Python package name (dashes are not permitted).

You might simply want to create a new branch off of `main` and then copy your `hls_stac_item.py` file over to the new branch you create. Then, I suggest you eliminate the `HlsViStacItem` class and simply convert all of its methods into functions. There's no need for a class in this case.

**Comment by SwordSaintLancelot** [comment]
Thanks for the heads up @chuckwondo . I will rebase the branch and work on getting the functions changed.

**Comment by chuckwondo** [comment]
@SwordSaintLancelot, I suggest simply creating a new branch off of `main`. Rebasing will likely be very problematic due to the significant number of moves/renames.

**Comment by chuckwondo** [comment]
Fixed by https://github.com/NASA-IMPACT/hls-vi/pull/21

**Comment by madhuksridhar** [comment]
@SwordSaintLancelot can we close this ticket?

**Comment by SwordSaintLancelot** [comment]
Yes.
